name: Build & Publish Web

on:
  push:
    branches: [ master ]

permissions:
  contents: read
  packages: write

jobs:
  build-publish:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_API_BASE_URL: ${{ secrets.API_BASE_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install deps & build
        run: |
          npm ci
          npm run build

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & tag Docker image
        run: |
          docker build \
            -t ghcr.io/${{ github.repository_owner }}/mokengeli-biloko-management:${{ github.sha }} \
            -t ghcr.io/${{ github.repository_owner }}/mokengeli-biloko-management:latest \
            .

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/mokengeli-biloko-management:${{ github.sha }}
          docker push ghcr.io/${{ github.repository_owner }}/mokengeli-biloko-management:latest
